spring:
  datasource:
    url: "jdbc:mysql://localhost/library"               # 접근하려는 mysql 주소 입력
    username: "root"                                    # 계정명
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver         # DB에 접근할 떄 사용하는 프로그램
  jpa:
    hibernate:
      ddl-auto: none                                    # 스피링이 시작할 때 DB에 있는 테이블을 어떻게 처리할지 / create, create-drop, update, validate, none
    properties:
      hibernate:
        show_sql: true                                  # JPA를 사용해 SQL을 DB에 날릴 때 SQL을 보여줄 것인가
        format_sql: true                                # SQL을 보여줄 떄 이쁘게 포맷팅 할 것인가
        dialect: org.hibernate.dialect.MySQL8Dialect    # 이 옵션을 통해 DB를 특정하면 조금씩 다른 SQL로 수정해준다.